# Generated by Django 2.0.1 on 2018-01-17 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='createticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('createdat', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('createdby', models.TextField()),
                ('priority', models.IntegerField()),
                ('assignedto', models.TextField()),
                ('userId', models.IntegerField()),
                ('ticketId', models.IntegerField()),
            ],
        ),
    ]
